name: AI Metrics Installation, Analysis, and Reporting
description: "Install necessary tools for generating AI Metrics for .NET projects, run the analysis, and publish the results."

inputs:
  sftp_server: 
    description: 'The SFTP server to which AI Metrics will be published.'
    required: true

  ai_path:
    description: 'The path within the container where AI Metrics will be published.'
    required: true

  coverage_path:
    description: 'The path within the container where code coverage files will be published.'
    required: true

  container_name:
    description: 'The name of the container where AI Metrics will be published.'
    required: true

  sas_key:
    description: 'The SAS key for authenticating to the storage account when publishing AI Metrics.'
    required: true

#outputs:

runs:
  using: "composite"

  steps:
    - name: Install AI Metrics Tools
      uses: xplor-pay/github-actions/.github/actions/dotnet/ai_metrics_install@main
      continue-on-error: true

    - name: Run AI Metrics Analysis
      uses: xplor-pay/github-actions/.github/actions/dotnet/ai_metrics_analyze@main
      continue-on-error: true

    - name: Publish AI Metrics Reports
      uses: xplor-pay/github-actions/.github/actions/dotnet/ai_metrics_publish@main
      with:
        sftp_server: ${{ inputs.sftp_server }}
        ai_path: ${{ inputs.ai_path }}
        coverage_path: ${{ inputs.coverage_path }}
        container_name: ${{ inputs.container_name }}
        sas_key: ${{ inputs.sas_key }}
      continue-on-error: true
