${SERVICE_NAME}:
  environment:
    SPRING.CONFIG.LOCATION: file:/opt/docker/properties/${SERVICE_NAME}/${SERVICE_ENV}/
    TRUST_STORE: ${TRUST_STORE}
    TRUST_PASSWD: ${TRUST_PASSWORD}
    _JAVA_OPTIONS: ${JAVA_OPTIONS}
  image: ${REGISTRY_NAME}/${SERVICE_NAME}:${IMAGE_VERSION}
  volumes:
    - /opt/docker/log/${SERVICE_NAME}:/opt/docker/log/${SERVICE_NAME}
    - /opt/docker/properties/${SERVICE_NAME}/${SERVICE_ENV}:/opt/docker/properties/${SERVICE_NAME}/${SERVICE_ENV}
    - /opt/docker/keys:/opt/docker/keys
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=${SERVICE_NAME}
