# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Continuous Integration

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: 'The .NET SDK version to use for the build and test steps.'
        required: true
        type: string
        default: '8.0.x'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore Dependencies
      run: |
          # Count .sln files in the root directory
          SLN_COUNT=$(find . -maxdepth 1 -name "*.sln" | wc -l)

          if [ "$SLN_COUNT" -gt 0 ]; then
            echo "✅ Found Solution file(s) in root. Restoring via .sln..."
            dotnet restore
          else
            echo "⚠️ No .sln found in root. Restoring all .csproj files recursively..."
            find . -name "*.csproj" -exec dotnet restore {} +
          fi
    
    - name: Build Repository
      run: dotnet build --configuration Release --no-restore
    
    - name: Run Tests
      run: > 
        dotnet test --configuration Release 
        --no-build 
        --no-restore 
        --verbosity normal 
        "--filter:TestCategory!~Integration&Category!~Integration" 
        --collect:"XPlat Code Coverage;Format=opencover,cobertura" 
        -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.SkipAutoProps=true DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Exclude=[*Tests*]* DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.ExcludeAssembliesWithoutSources=MissingAll DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.SingleHit=false DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.IncludeTestAssembly=true DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.UseSourceLink=false DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.DeterministicReport=false DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.ExcludeByAttribute=Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute,ExcludeFromCodeCoverageAttribute'

    - name: Enforce .editorconfig Code Styles
      run: dotnet format --verbosity detailed --verify-no-changes
